services:
  web:
    container_name: app-mathilde-web-prod
    build: .
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production
      PORT: 5173
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true