version: '3.8'
services:
  web:
    container_name: ia-marketplace-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - dokploy-network
    environment:
      NODE_ENV: production
      PORT: 80
      HOSTNAME: 0.0.0.0
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
