services:
  web:
    container_name: app-mathilde-web-prod
    build: .
    ports:
      - "5173:80"
    environment:
      NODE_ENV: production
      # Puerto del servidor
      PORT: 80
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
    networks:
      - dokploy-network

  # Servicio de desarrollo (opcional)
  web-dev:
    container_name: app-mathilde-web-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5174:5174"
    environment:
      NODE_ENV: development
      # Puerto del servidor de desarrollo
      PORT: 5174
      HOSTNAME: 0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    profiles:
      - dev
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true